<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageVersion>10.0.0</PackageVersion>
    <Authors>The C# Author</Authors>
    <Description>Server Utilities</Description>
  </PropertyGroup>

</Project>
